import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import './globals.css'
import { cn } from '@/lib/utils'
import CommandBar from '@/components/common/command-bar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={cn(
          'text-primary bg-background antialiased',
          GeistSans.className,
        )}
      >
        <CommandBar>{children}</CommandBar>
      </body>
    </html>
  )
}
