import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans'
import '../globals.css'
import { cn } from '@/lib/utils'
import CommandBar from '@/components/common/command-bar'
import Header from '@/components/layout/header'
import Footer from '@/components/layout/footer'

import { NextIntlClientProvider } from 'next-intl'
import { getMessages } from 'next-intl/server'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode
  params: { locale: string }
}>) {
  const messages = await getMessages()

  return (
    <html lang={locale}>
      <CommandBar>
        <body
          className={cn(
            'bg-background text-primary antialiased',
            GeistSans.className,
          )}
        >
          <div className="relative z-0 flex min-h-screen flex-col">
            <Header />
            <main className="container flex flex-1 overflow-hidden">
              <NextIntlClientProvider messages={messages}>
                {children}
              </NextIntlClientProvider>
            </main>
            <Footer />
          </div>
        </body>
      </CommandBar>
    </html>
  )
}
